Added docstring for concat
narwhals-dev/narwhals pull request #808
Opened 2024-08-18 10:55 UTC by Sherwin-14

I wrote the docstring's for concat function. Please have a look into it

2024-08-18 11:19 UTC, MarcoGorelli reviewed
nice one @Sherwin-14 , thanks!

a few requests:
- could we make `data_1`, `data_2` please? and then `df_pd_1`, `df_pd_2`, `df_pl_1`, `df_pl_2`?
- could you check your statement about `Series`? I don't think we support them

2024-08-18 11:27 UTC, Sherwin-14 commented
Thanks for the feedback, Marc! The CI tests seem to be failing though and I can't figure it out why, any clues?

2024-08-18 11:38 UTC, Sherwin-14 commented
> * df_pd_1

Hey, needed some clarification over this. I have changed both the data's to `data_1` and `data_2` but I am confused as to how we can change df it to `df_pd_1` or ` df_pl_1` ?

2024-08-18 12:30 UTC, FBruzzesi reviewed
Thanks for the PR. I have only one comment in addition to what Marco already mentioned.

Regarding the test failing, that's because we compare the exposed functions with what we expose in [`/stable/v1.py`](https://github.com/narwhals-dev/narwhals/blob/main/narwhals/stable/v1.py). I think this was not failing before because the docstring was empty. Now it should be added.

Here a hint on how to:

```py
def concat(
    items: Iterable[FrameT],
    *,
    how: Literal["horizontal", "vertical"] = "vertical",
) -> FrameT:
    # Same docstring but using 
    # import narwhals.stable.v1 as nw 
    # inplace of import narwhals as nw
    
    return _stableify(nw.concat(items, how=how))
```

2024-08-18 12:30 UTC, FBruzzesi commented on narwhals/functions.py
> +    """
Would you mind adding an example for horizontal concat as well?

2024-08-18 12:41 UTC, MarcoGorelli commented
> I have changed both the data's to data_1 and data_2 but I am confused as to how we can change df to df_pd_1 or  df_pl_1 ?

you can do
```
data_1 = ...
data_2 = ...
df_pd_1 = pd.DataFrame(data_1)
df_pd_2 = pd.DataFrame(data_2)
df_pl_1 = pl.DataFrame(data_1)
df_pl_2 = pl.DataFrame(data_2)
```

2024-08-19 17:41 UTC, MarcoGorelli reviewed
thanks for updating!

2024-08-19 17:41 UTC, MarcoGorelli commented on narwhals/functions.py
> +        ...     native_namespace_df2 = nw.get_native_namespace(df2)
why do you need this?

2024-08-19 17:41 UTC, MarcoGorelli commented on narwhals/functions.py
> +
i think we can just remove this, the arguments section already shows what's supported

2024-08-19 17:41 UTC, MarcoGorelli commented on narwhals/functions.py
> +        ...     native_namespace_df2 = nw.get_native_namespace(df2)
same

2024-08-20 09:16 UTC, MarcoGorelli approved these changes
nice one, thanks @Sherwin-14 !

![](https://i.fluffy.cc/g6TR0RVJMJ4f5nWrDR39tNrddc3gNSdm.gif)

2024-08-20 09:16 UTC, MarcoGorelli commented on narwhals/functions.py
> +        >>> data_2 = {"c": [5, 2], "d": [1, 4]}
```suggestion
        >>> data_1 = {"a": [1, 2, 3], "b": [4, 5, 6]}
        >>> data_2 = {"c": [5, 2], "d": [1, 4]}
```

2024-08-20 09:32 UTC, MarcoGorelli requested changes
one more thing (as ci is failing)

can you update the docstring for `concat` in `narwhals/stable/v1` as well please? it should be the same, but with `import narwhals.stable.v1 as nw` instead of `import narwhals as nw`

2024-08-21 08:04 UTC, Sherwin-14 commented
> one more thing (as ci is failing)
> 
> can you update the docstring for `concat` in `narwhals/stable/v1` as well please? it should be the same, but with `import narwhals.stable.v1 as nw` instead of `import narwhals as nw`

Hey I checked the  `narwhals/stable/v1` file and I did not find concat function there

2024-08-25 10:37 UTC, Sherwin-14 commented
> > one more thing (as ci is failing)
> > can you update the docstring for `concat` in `narwhals/stable/v1` as well please? it should be the same, but with `import narwhals.stable.v1 as nw` instead of `import narwhals as nw`
> 
> Hey I checked the `narwhals/stable/v1` file and I did not find concat function there

Hey did you find some solution for this? the ci is still failing and I didn't find the `concat` function in `stable/v1/`.

2024-08-25 17:23 UTC, FBruzzesi commented
Hey @Sherwin-14 , sorry I missed the first comment among various notifications.

I now see the issue, we somehow have the `concat` in `stable/v1.py` out of sync, or even worse, not even `_stableify`-ed yet.
@MarcoGorelli I think we can do that in another PR as it seems a bit out of scope for this one?

2024-08-25 17:33 UTC, MarcoGorelli commented
thanks for the ping, and sorry for the delay

in `v1.py`, `concat` currently just gets imported and re-exported:
```
from narwhals.functions import concat
```

so yes, maybe a separate PR to add a docstring to `concat` and stableify it would be good 👍

2024-08-25 17:52 UTC, Sherwin-14 commented
No worries. I can do this but what exactly needs to be done here? If you can outline the steps to me it will be a little bit easier for me.

2024-08-25 17:57 UTC, MarcoGorelli commented
thanks!

you'll need to do something like
```diff
diff --git a/narwhals/stable/v1.py b/narwhals/stable/v1.py
index 9c7c2d15..d96f0523 100644
--- a/narwhals/stable/v1.py
+++ b/narwhals/stable/v1.py
@@ -37,7 +37,7 @@ from narwhals.expr import Expr as NwExpr
 from narwhals.expr import Then as NwThen
 from narwhals.expr import When as NwWhen
 from narwhals.expr import when as nw_when
-from narwhals.functions import concat
+from narwhals.functions import concat as nw_concat
 from narwhals.functions import show_versions
 from narwhals.schema import Schema as NwSchema
 from narwhals.series import Series as NwSeries
@@ -1668,6 +1668,9 @@ def from_dict(
         nw.from_dict(data, schema=schema, native_namespace=native_namespace)
     )
 
+def concat(*args, **kwargs):
+    return _stableify(nw_concat(*args, **kwargs))
+
 ```
but instead of `*args` and `**kwargs`, put the actual variable names from the `concat` signature

2024-08-25 18:00 UTC, MarcoGorelli commented
looks like Francesco's already on it in  #869 though ⚡

2024-08-26 17:39 UTC, FBruzzesi commented
Hey @Sherwin-14 , we just merged a PR that adds `concat` function in `stable/v1.py`. Now you should be able to proceed with this PR after merging main branch

2024-08-27 17:32 UTC, Sherwin-14 commented
Thanks a lot. I will do the needful :)

2024-09-01 10:46 UTC, MarcoGorelli commented
thanks @Sherwin-14 ! i think maybe something went wrong when merging, as docs/api-completeness.md is being shown as modified

2024-09-01 10:55 UTC, Sherwin-14 commented
> thanks @Sherwin-14 ! i think maybe something went wrong when merging, as docs/api-completeness.md is being shown as modified

Yeah I fixed that you can take a look at it now :)

2024-09-01 12:15 UTC, MarcoGorelli approved these changes
this is really good - thanks @Sherwin-14 , and @FBruzzesi for review!

![](https://i.fluffy.cc/6KVxTshxMsrtB8MjZ7MHvlvBCJjftgtP.gif)

2024-09-01 12:43 UTC, Sherwin-14 commented
> this is really good - thanks @Sherwin-14 , and @FBruzzesi for review!
> 
> ![](https://camo.githubusercontent.com/2f3443f5f57e94310b336cd66d7ca304fdcc6cf79cdbf49e222decf6295927dc/68747470733a2f2f692e666c756666792e63632f364b5678547368784d73727442384d6a5a374d48766c7642434a6a66746774502e676966) [ ](https://camo.githubusercontent.com/2f3443f5f57e94310b336cd66d7ca304fdcc6cf79cdbf49e222decf6295927dc/68747470733a2f2f692e666c756666792e63632f364b5678547368784d73727442384d6a5a374d48766c7642434a6a66746774502e676966) ![68747470733a2f2f692e666c756666792e63632f364b5678547368784d73727442384d6a5a374d48766c7642434a6a66746774502e676966](https://camo.githubusercontent.com/2f3443f5f57e94310b336cd66d7ca304fdcc6cf79cdbf49e222decf6295927dc/68747470733a2f2f692e666c756666792e63632f364b5678547368784d73727442384d6a5a374d48766c7642434a6a66746774502e676966) [ ](https://camo.githubusercontent.com/2f3443f5f57e94310b336cd66d7ca304fdcc6cf79cdbf49e222decf6295927dc/68747470733a2f2f692e666c756666792e63632f364b5678547368784d73727442384d6a5a374d48766c7642434a6a66746774502e676966)

2024-09-01 13:05 UTC, merged